---@type LazySpec
return {
  "AstroNvim/astrocommunity",
  { import = "astrocommunity.pack.lua" },
  -- { import = "astrocommunity.pack.biome" },
  -- { import = "astrocommunity.pack.nvchad-ui" },
  { import = "astrocommunity.pack.typescript" },
  -- { import = "astrocommunity.color.modes-nvim" },
  -- { import = "astrocommunity.color.vim-highlighter" },
  -- { import = "astrocommunity.bars-and-lines.wakastat" },
  -- { import = "astrocommunity.pack.python" },
  -- { import = "astrocommunity.pack.tailwindcss" },
  -- { import = "astrocommunity.pack.rainbow-delimiter-indent-blankline" },
  -- { import = "astrocommunity.color.transparent-nvim" },
  { import = "astrocommunity.colorscheme.tokyonight-nvim" },
  { import = "astrocommunity.colorscheme.catppuccin" },
  { import = "astrocommunity.colorscheme.rose-pine" },
  { import = "astrocommunity.git.vscode-diff-nvim" },
  { import = "astrocommunity.colorscheme.bamboo-nvim" },
  { import = "astrocommunity.terminal-integration.vim-tmux-navigator" },
  { import = "astrocommunity.markdown-and-latex.render-markdown-nvim" },
  -- { import = "astrocommunity.editing-support.nvim-context-vt" },
  -- { import = "astrocommunity.diagnostics.trouble-nvim" },
  -- { import = "astrocommunity.editing-support.cloak-nvim" },
  -- { import = "astrocommunity.editing-support.todo-comments-nvim" },
  -- { import = "astrocommunity.editing-support.rainbow-delimiters-nvim" },
  -- { import = "astrocommunity.completion.cmp-nerdfont" },
  -- { import = "astrocommunity.completion.blink-cmp" },
  -- { import = "astrocommunity.recipes.vscode-icons" },
  -- { import = "astrocommunity.icon.mini-icons" },
  -- { import = "astrocommunity.lsp.ts-error-translator-nvim" },
  { import = "astrocommunity.recipes.disable-borders" }, -- do not go well with nvchad
  -- { import = "astrocommunity.recipes.diagnostic-virtual-lines-current-line" },
  { import = "astrocommunity.motion.flash-nvim" },
  { import = "astrocommunity.editing-support.ultimate-autopair-nvim" },
  { import = "astrocommunity.editing-support.zen-mode-nvim" },
  { import = "astrocommunity.scrolling.vim-smoothie" },
  { import = "astrocommunity.scrolling.satellite-nvim" },
}
